---
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  index.number_of_replicas: 0

setup.kibana:
  host: "${KIBANA_HOST:kibana:5601}"

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

logging.json: true
logging.metrics.enabled: false

monitoring.enabled: true

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
###################################################################################################
## autodiscover
###################################################################################################
filebeat.autodiscover:
  providers:

http.enabled: true
http.host: localhost
http.port: 5066
