---
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS:elasticsearch:9200}"]

setup.kibana:
  host: "${KIBANA_HOST:kibana:5601}"

processors:
  - add_observer_metadata:
      geo:
        name: DevOpsDays-Taipei-2022

heartbeat.monitors:
heartbeat.scheduler:
  limit: 10

heartbeat.autodiscover:
  providers:

http.enabled: true
http.host: localhost
http.port: 5066
monitoring.enabled: true